services:
  tm-roadmap-prd:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tm-roadmap-prd
    restart: always
    environment:
      - DATABASE_URL=sqlite:////app/data/tm_roadmap.db
    volumes:
      - hermes_roadmap_data:/app/data
    networks:
      - tm-network

networks:
  tm-network:
    external: true

volumes:
  hermes_roadmap_data:
    name: hermes_roadmap_data_prd
